// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAqxdENVI4Buf4XuJ1wMbX2NFpErPwTuc',
    appId: '1:509773065963:web:5aa2a99a277ed36b7218ae',
    messagingSenderId: '509773065963',
    projectId: 'slide-it-rating',
    authDomain: 'slide-it-rating.firebaseapp.com',
    storageBucket: 'slide-it-rating.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB44RFSppi1j6Rb7CtpyBGfxcFQOoZC2io',
    appId: '1:509773065963:android:e11cd1bc133fa59a7218ae',
    messagingSenderId: '509773065963',
    projectId: 'slide-it-rating',
    storageBucket: 'slide-it-rating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPPNDMZKDVGeEHUpHY6XhZX2PN47Lt7Gg',
    appId: '1:509773065963:ios:fcc80f38b491ad8d7218ae',
    messagingSenderId: '509773065963',
    projectId: 'slide-it-rating',
    storageBucket: 'slide-it-rating.appspot.com',
    iosClientId: '509773065963-tpe7h0ptvbujqq01vt2va6d5logbdrh8.apps.googleusercontent.com',
    iosBundleId: 'de.timdavidfriedrich.rating',
  );
}
